language: minimal
services:
  - docker
before_script:
  - docker-compose build
  - docker-compose up -d db
  - docker-compose up -d selenium
  - docker-compose run --rm --no-deps app ./bin/setup
  - docker-compose run --rm --no-deps app rake db:test:prepare
script:
  - docker-compose run app bundle exec rake spec tmp:clear
deploy:
  provider: script
  script: "./build.sh"
  on:
    all_branches: true
