version: '2.0'

x-defaults:
  base: &base
    platform: linux/amd64
    image: bcardiff/themis:devenv-recovery-clean
    environment:
      RAILS_ENV:
      DATABASE_HOST: db
      SELENIUM_URL: http://selenium:4444/
      SETTINGS__SMTP_SETTINGS__ADDRESS: smtp
      SETTINGS__SMTP_SETTINGS__PASSWORD: smtp
      SETTINGS__SMTP_SETTINGS__PORT: 1025
      SETTINGS__SMTP_SETTINGS__USER_NAME: smtp
      SETTINGS__SMTP_DEFAULT_OPTIONS__FROM: info@swingcity.com.ar
    pid: host
    working_dir: /src
    depends_on:
      - db
      - smtp
    volumes:
      - .:/src
      - bundle:/usr/local/bundle

services:
  app:
    <<: *base
    ports:
      - "3000:3000"
    command: /bin/sh -c 'bundle exec ./bin/rails s -b 0.0.0.0'

  db:
    platform: linux/amd64
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - db:/var/lib/mysql
      - .:/src # to load backups

  smtp:
    platform: linux/amd64
    image: 'djfarrelly/maildev'
    command: 'bin/maildev --web 3080 --smtp 1025 --incoming-user smtp --incoming-pass smtp'
    ports:
      - '3080:3080'

  selenium:
    platform: linux/amd64
    image: selenium/standalone-firefox
    ports:
      - "5901:5900"
    shm_size: 2g
    volumes:
      - .:/app

volumes:
  db:
  bundle:
