version: '2.0'

x-defaults:
  base: &base
    build:
      context: .
      dockerfile: Dockerfile-dev
    environment:
      RAILS_ENV:
      DATABASE_HOST: db
      SELENIUM_URL: http://selenium:4444/
      SETTINGS__SMTP__ADDRESS: smtp
      SETTINGS__SMTP__PASSWORD: smtp
      SETTINGS__SMTP__PORT: 1025
      SETTINGS__SMTP__USER_NAME: smtp
    pid: host
    working_dir: /src
    depends_on:
      - db
      - smtp
    volumes:
      - .:/src
      - bundle:/usr/local/bundle

services:
  app:
    <<: *base
    ports:
      - "3000:3000"
    command: /bin/sh -c 'bundle exec ./bin/rails s -b 0.0.0.0'

  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - db:/var/lib/mysql
      - .:/src # to load backups

  smtp:
    image: 'djfarrelly/maildev'
    command: 'bin/maildev --web 3080 --smtp 1025 --incoming-user smtp --incoming-pass smtp'
    ports:
      - '3080:3080'

  selenium:
    image: selenium/standalone-firefox-debug
    # image: selenium/standalone-firefox
    shm_size: 2g
    volumes:
      - .:/app
    ports:
      - '5901:5900'

volumes:
  db:
  bundle:
