name: CI

on:
  push:
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 6 * * 1'  # Every monday 6 AM

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v2

      - name: Prepare
        run: |
          docker-compose build
          docker-compose up -d db
          docker-compose up -d selenium
          docker-compose run --rm --no-deps app ./bin/setup
          docker-compose run --rm --no-deps app rake db:test:prepare

      - name: Run specs
        run: |
          docker-compose run app bundle exec rake spec tmp:clear
